package lanou.com.gifttalk.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import lanou.com.gifttalk.greendao.BuildTypeBean;

import lanou.com.gifttalk.greendao.BuildTypeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig buildTypeBeanDaoConfig;

    private final BuildTypeBeanDao buildTypeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        buildTypeBeanDaoConfig = daoConfigMap.get(BuildTypeBeanDao.class).clone();
        buildTypeBeanDaoConfig.initIdentityScope(type);

        buildTypeBeanDao = new BuildTypeBeanDao(buildTypeBeanDaoConfig, this);

        registerDao(BuildTypeBean.class, buildTypeBeanDao);
    }
    
    public void clear() {
        buildTypeBeanDaoConfig.clearIdentityScope();
    }

    public BuildTypeBeanDao getBuildTypeBeanDao() {
        return buildTypeBeanDao;
    }

}
