package lanou.com.gifttalk.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import lanou.com.gifttalk.greendao.BuildTypeBean;
import lanou.com.gifttalk.greendao.MyCollect;

import lanou.com.gifttalk.greendao.BuildTypeBeanDao;
import lanou.com.gifttalk.greendao.MyCollectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig buildTypeBeanDaoConfig;
    private final DaoConfig myCollectDaoConfig;

    private final BuildTypeBeanDao buildTypeBeanDao;
    private final MyCollectDao myCollectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        buildTypeBeanDaoConfig = daoConfigMap.get(BuildTypeBeanDao.class).clone();
        buildTypeBeanDaoConfig.initIdentityScope(type);

        myCollectDaoConfig = daoConfigMap.get(MyCollectDao.class).clone();
        myCollectDaoConfig.initIdentityScope(type);

        buildTypeBeanDao = new BuildTypeBeanDao(buildTypeBeanDaoConfig, this);
        myCollectDao = new MyCollectDao(myCollectDaoConfig, this);

        registerDao(BuildTypeBean.class, buildTypeBeanDao);
        registerDao(MyCollect.class, myCollectDao);
    }
    
    public void clear() {
        buildTypeBeanDaoConfig.clearIdentityScope();
        myCollectDaoConfig.clearIdentityScope();
    }

    public BuildTypeBeanDao getBuildTypeBeanDao() {
        return buildTypeBeanDao;
    }

    public MyCollectDao getMyCollectDao() {
        return myCollectDao;
    }

}
